CC ?= tcc
CFLAGS := -std=c99 -Wall -Wextra -Wpedantic -O3
LDFLAGS += -lmingw32 -lSDL2main -lcomdlg32 -lole32 -lshlwapi \\
		-lSDL2 -lSDL2_ttf -lSDL2_image -lfontconfig
SRC := src/*.c
EXE := sslide

sslide: src/*.h src/*.c
	$(CC) $(SRC) -o $(EXE) $(CFLAGS) $(LDFLAGS)

